version: "3.8"

networks:
  evolution-net:
    name: evolution-net
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMq
    networks:
      - evolution-net
    ports:
      - "5672:5672" # Porta para comunicação com clientes (AMQP)
      - "15672:15672" # Porta da interface web de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
