
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672" 
    hostname: rabbitmq-sandbox
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

